# Generated by Django 5.2.15 on 2026-07-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='NONE', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drone_f722_command',
            },
        ),
        migrations.CreateModel(
            name='DroneStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_mode', models.CharField(default='DISARM', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('speed', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('roll', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pitch', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('yaw', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('battery_voltage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('battery_percentage', models.IntegerField(default=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drone_f722_status',
                'ordering': ['-timestamp'],
            },
        ),
    ]
