# Generated by Django 5.2.15 on 2026-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_dronecommand_status_dronecommand_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('AUTO_GPS', 'Auto GPS / Map'), ('MANUAL', 'Manual Control')], default='AUTO_GPS', max_length=20)),
                ('throttle', models.IntegerField(default=0)),
                ('yaw', models.IntegerField(default=0)),
                ('pitch', models.IntegerField(default=0)),
                ('roll', models.IntegerField(default=0)),
                ('altitude', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('speed', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dronestatus',
            name='pitch',
        ),
        migrations.RemoveField(
            model_name='dronestatus',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='dronestatus',
            name='yaw',
        ),
    ]
