# Generated by Django 5.2.15 on 2026-07-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_manualcontrollog_remove_dronestatus_pitch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualcontrollog',
            name='command_type',
        ),
    ]
