# Generated by Django 5.2.15 on 2026-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_manualcontrollog_command_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronecommand',
            name='altitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dronecommand',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
