# Generated by Django 5.2.15 on 2026-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_dronecommand_altitude_dronecommand_speed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManualControlLog',
        ),
        migrations.RenameField(
            model_name='dronecommand',
            old_name='latitude',
            new_name='lat1',
        ),
        migrations.RenameField(
            model_name='dronecommand',
            old_name='longitude',
            new_name='lat2',
        ),
        migrations.AddField(
            model_name='dronecommand',
            name='lon1',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dronecommand',
            name='lon2',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dronecommand',
            name='pitch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dronecommand',
            name='roll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dronecommand',
            name='throttle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dronecommand',
            name='yaw',
            field=models.IntegerField(default=0),
        ),
    ]
