# Generated by Django 5.2.15 on 2026-07-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_manualcontrollog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dronestatus',
            name='battery_voltage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
